src/Dywt.Web/Controllers/DayController.cs
using Dywt.App;
using Dywt.App.Commands;
using Dywt.App.Infrastructure;
using Dywt.App.Models;
using Dywt.Web.Framework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Dywt.Web.Controllers
{
    [Authorize]
    public class DayController : DywtController
    {
        public ActionResult Entry(DateTime? date)
        {
            if(!date.HasValue)
            {
                var today = UserTime.LocalNow().Date;
                return RedirectToAction("Entry", new { date = today.ToString("yyyy-MM-dd") });
            }

            var model = ModelBuilder.Create<DateTime, DayEntryModel>(date.Value);
            return View(model);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Entry(DayEntryCommand command)
        {
            CommandBus.Execute(command);
            Notifier.Success("Entry saved for {0}", command.Date);
            return RedirectToAction("Index", "Month", new { command.Date.Year, command.Date.Month });
        }
    }
}

src/Dywt.Web/Controllers/MonthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dywt.App.Models;
using Dywt.Web.Framework;

namespace Dywt.Web.Controllers
{
    [Authorize]
    public class MonthController : DywtController
    {
        public ActionResult Index(int year, int month)
        {
            var date = new DateTime(year, month, 1);

            var model = ModelBuilder.Create<DateTime, MonthViewModel>(date);

            return View(model);
        }
    }
}

src/Dywt.Web/Views/Month/Index.cshtml
@using Dywt.App.Infrastructure
@using Dywt.Web
@model Dywt.App.Models.MonthViewModel

@{
    ViewBag.Title = Model.TheFirst.ToString("MMMM yyyy");
}

<div class="nav" role="navigation">
    <a href="@Url.Action("Index", new { year = Model.PreviousMonth.Year, month = Model.PreviousMonth.Month })">&lt; @Model.PreviousMonth.ToString("MMMM")</a>
    | <a href="@Url.Action("Index", new { year = Model.NextMonth.Year, month = Model.NextMonth.Month })">@Model.NextMonth.ToString("MMMM") &gt;</a>
</div>

<h2>@ViewBag.Title - @string.Format("{0:0.#}", Model.DaysWorked) days</h2>

<ol class="calendar cf">
    @foreach(var tile in Model.Tiles)
    {
        <li class="@((tile.Date.Month != Model.TheFirst.Month).ToLabels("filler", "")) @((tile.Date == UserTime.LocalNow().Date).ToLabels("today", ""))">
            <a href="@Url.Action("Entry", "Day", new { date = tile.Date.ToString("yyyy-MM-dd") })" data-current-answer="@tile.HoursWorked">
                <span class="day" aria-hidden="true" role="presentation">@((tile.Date == UserTime.LocalNow().Date).ToLabels("Today", tile.Date.Day.ToString()))</span>
                <h3>@tile.Date.ToShortDateString()</h3>
                <p>
                    @if (tile.HoursWorked.HasValue)
                    {
                        @tile.HoursWorked.Value <span>h</span>
                    }
                    else
                    {
                        <text>&nbsp;</text>
                    }
                </p>
            </a>
        </li>
    }
</ol>